import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import "@/styles/globals.css";
import Nav from "@/components/navbar/nav";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redHatDisplay.className} antialiased pt-12 w-screen h-dvh`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
